### ISSUE TITLE
[BUG] navigator_interfaces groups does not exists

### ISSUE THREAD

**Issue by Raph-xyz** [evereux/pycatia#152]
**Describe the bug**
pycatia.navigator_interfaces.groups class member does not exists, while it is in the code and in the documentation

**To Reproduce**
import pycatia
group1 = pycatia.navigator_interfaces.groups.Groups.add()

Error :
```
 [2023-08-03 16:45:27,190] INFO in documents: Creating a new "Product".
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\RaphaelBIET\repo\c-checker\coordinator\catiaClash.py", line 33, in main
    group1 = pycatia.navigator_interfaces.groups.Groups.add()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pycatia.navigator_interfaces' has no attribute 'groups'. Did you mean: 'group'?
```

**Expected behavior**
A group is added to the document

**Screenshots**
![image](https://github.com/evereux/pycatia/assets/23099749/98d956d9-189f-428d-aeb5-7d9b174b667f)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - CATIA V5 version [V5-6R2017]
 - pycatia version [0.5.8]

**Additional context**
I can access the pycatia.navigator_interfaces.group member, but I need to add one before, through the groups

**Comment by Raph-xyz** [comment]
Sorry, got confused with Catia scripting model, I found how this is supposed to work
